Algoritmo "comversaominutos"
// disciplina:[linguadem de programação]
// professor: Cintia pinho
// Descrição   : convertera o minuo em hora
// Autor(a)    : Brenda Cristina
// Data atual  : 19/05/2020
Var
hora,minuto,convert:real


Inicio
//entrada
escreva("que horas é?:")
leia(hora)
escreva("qual é o minuto?:")
leia(minuto)

//processamento
convert<-(minuto/60)+hora

//saida
escreva("a comversao da minuto pra horas é de:", convert)


Fimalgoritmo