Algoritmo "dolar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   : calcula o valor do dolar e converte em reias
// Autor(a)    : Brenda Cristina
// Data atual  : 18/05/2020
Var
dolar,valor,result:real


Inicio
//entrada
escreva("qual o valor do dolar hoje:")
leia(dolar)
escreva("quantos voce quer converter?")

//processamento
result<-valor/dolar

//saida
escreva("voce tem:$",result)


Fimalgoritmo