Algoritmo "idadehabilitacao"
// Descrição   : ira te inormar se voce podera passarou nao
// Autor(a)    :
// Data atual  : 22/06/2020
Var
idade:inteiro
resp:caracter

Inicio
//entrada
escreval("qual sua idade: " )
leia(idade)
escreval("possui habilitacao: " )
leia(resp)

//descrição

se((idade>=18) e (resp"sim")) entao

        escreval("pode passar:")

senao
        escreval("nao pode passar:")
finse


Fimalgoritmo