algoritmo "leresomarnumeros"
// Função :ler e somar numeros ate o valor ser 0
// Autor : Benda Cristina
// Data : 15/09/2020
// Seção de Declarações 
var
 soma, numeros: inteiro
inicio

 numeros <- 1
 soma <- 0
 enquanto numeros <> 0 faca
 escreval("Digite um numero:")
 leia(numeros)

 soma <- soma + numeros
 fimenquanto
 escreval("O resultado da soma dos numeros é: ", soma)
fimalgoritmo
