algoritmo "melhorescola"
// Função :inormar qual a melhor escola de Ribeirão Pires
// Autor :Brenda Cristina
// Data : 16/09/2020
var
nome:caractere
inicio

  escreval("************QUAL A MELHOR ESCOLA DE RIBEIRÃO PIRES?*************")

repita
  escreval("informe qual a melhor escola de Ribeirão Pires:")
  leia(nome)
  
escreval("QUE PENA!VOCE NOS INFORMOU A ESCOLA ERRADA:")

ate(nome="ETEC MCM:")

 escreval("PARABENS VOCE NOS INFORMOU A ESCOLA CORRETA:")
 fimalgoritmo
