Algoritmo "valorcusto"
// disciplina: [Linguagem e programação]
//professor :Cintia Pinho
// Descrição   : calculara o valor de um certo custo
// Autor(a)    :Brenda Cristina
// Data atual  : 18/05/2020
Var
custo,porcentagem,valor:real


Inicio
//entrada
escreva("qual o valor do custo?:")
leia(custo)

//processamento
valor<-(custo*1.45*1.28)

//saida
escreva("o valor total é:",valor)


Fimalgoritmo